# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 07d8964f2840a21ffa1e7cfb2db715d287c8585ae10107c145a97eaf1d57794c169ffa20203fee541c4f86de50c27aab46a0e03a9a13af676eece2516d52235b

test:
  secret_key_base: fe98a50774da29519b99b9e3e5fb398b470bb0492e51d424b3470ada9a378458905aca7ad62aa60fbf261325f33b0fc9ea23dcb9752ad8b72fd1f4cc6c5acf4e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
